[book]
authors = ["徐沛"]
language = "zh"
multilingual = false
src = "src"
title = "XUPEI's Research"

[output.html]
no-section-label = true
mathjax-support = true
theme = "theme"
default-theme = "light"
preferred-dark-theme = "ayu"


[output.html.fold]
enable = true
level = 1

[preprocessor.katex]
after = ["links"]

[preprocessor.toc]
marker = "[TOC]"

